### ISSUE TITLE
Error showing in logs from netty

### ISSUE THREAD

**Issue by czf** [jurmous/etcd4j#126] opened 2016-09-20 01:16 UTC
```
public void Put(String key, String value) {
        try(EtcdClient etcd = new EtcdClient(_endpoints)){
            etcd.put(key,value).send().get();
        } catch (IOException |EtcdException | TimeoutException | EtcdAuthenticationException e) {
            e.printStackTrace();
            logger.error(e);
        }
    }
```

I based the above on the examples from the readme.  Calling `Put("key","value");`   I see the following in my logs.

> [ERROR|io.netty.util.concurrent.DefaultPromise.rejectedExecution|DefaultPromise] Failed to submit a listener notification task. Event loop shut down?
> java.util.concurrent.RejectedExecutionException: event executor terminated
>   at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:840)
>   at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:342)
>   at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:335)
>   at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
>   at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767)
>   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435)
>   at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120)
>   at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
>   at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1022)
>   at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:620)
>   at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:475)
>   at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964)
>   at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234)
>   at io.netty.resolver.dns.DnsNameResolver.close(DnsNameResolver.java:310)
>   at io.netty.resolver.dns.InflightNameResolver.close(InflightNameResolver.java:61)
>   at io.netty.resolver.InetSocketAddressResolver.close(InetSocketAddressResolver.java:94)
>   at io.netty.resolver.AddressResolverGroup$1.operationComplete(AddressResolverGroup.java:79)
>   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
>   at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
>   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
>   at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
>   at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:438)
>   at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:233)
>   at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
>   at java.lang.Thread.run(Thread.java:745)

Is there something that I can do to prevent this from bloating my logs?

**Comment by czf** [comment] 2016-09-21 21:07
I've tried reproducing this with the current version of master.   I don't see it happening.  

I downloaded the 2.12 source and tried reproducing in a unit test.  I didn't see this message displayed.  I created a simple main method with the try/catch explicit in the program.  Running that I saw this message again.  I tried doing the exact same main method with the master version and wasn't able to see the message displayed.

**Comment by wenhuancui** [comment] 2016-11-04 12:12
I got the same error, but to me the time seems to be when EtcdClient.close() is called
`
19:59:24.009 INFO main EtcdNettyClient - Shutting down Etcd4j Netty client
19:59:24.009 DEBUG main EtcdNettyClient - Shutting down Netty Loop
19:59:24.010 DEBUG main EtcdNettyClient - Shutting down Netty Timer
19:59:26.114 DEBUG nioEventLoopGroup-2-2 PoolThreadCache - Freed 2 thread-local buffer(s) from thread: nioEventLoopGroup-2-2
19:59:26.115 DEBUG nioEventLoopGroup-2-1 PoolThreadCache - Freed 2 thread-local buffer(s) from thread: nioEventLoopGroup-2-1
19:59:26.118 ERROR globalEventExecutor-1-1 rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated`

**Comment by wenhuancui** [comment] 2016-11-05 04:29
After I change the version to 2.11.0, this error is gone. Also for the 2.12.0 version, any get() call will hang when used in Spring Boot application.

**Comment by lburgazzoli** [comment] 2016-11-05 07:06
Version 2.12 requires jackson 2.8.x si I guess spring boot > 1.4. The warning is because of netty, does it happens also building from master?

**Comment by wenhuancui** [comment] 2016-11-10 09:05
@lburgazzoli Haven't tried that, and yes I was using spring boot < 1.4. That may be the cause. I will confirm it.

**Comment by lburgazzoli** [comment] 2016-11-22 13:51
@wenhuancui I've pushed a new 2.13.0 snapshot, would you mind to test against it ?

**Comment by lburgazzoli** [comment] 2017-01-13 10:50
Closed as no feedback from reporter

**Closed by lburgazzoli** 2017-01-13 10:50 UTC
